channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastqc
  - trimmomatic
  - parallel
  - multiqc
  - kraken2
  - kraken-biom
  - numpy
  - biom-format
  - pandas
  - python=3.11
  - r-base=4.3
  - bash_kernel=0.9.0
  - coreutils=9.1
  - r-phyloseq
  - r-ggplot2
