channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastqc
  - trimmomatic
  - parallel
  - multiqc
  - kraken2
  - kraken-biom
  - numpy
  - biom-format
  - pandas
  # --- R and microbiome analysis ---
  - r-base=4.3
  - r-essentials
  - bioconductor-phyloseq
  - bioconductor-biomformat
  - bioconductor-rhdf5
  # CRAN packages (from conda-forge)
  - r-microeco
  - r-file2meco
  - r-ggplot2
  - r-cowplot
  - r-rcolorbrewer
